name: projet-jardin-compose



services:
  jardin-mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projet_jardin
    networks:
      - projet-jardin
    ports:
      - "3314:3306"

  java:
    #image: projet-jardin-java:latest
    
    # Pour utiliser un Dockerfile (Docker fera un Docker Build)
    build:
      context: ../projet-jardin # Le nom du répertoire dans lequel se trouve le fichier Dockerfile
    image: java

    container_name: projet-jardin-java
    ports:
      - 8091:8080
    networks:
      - projet-jardin

  angular:
    #image: projet-jardin-java:latest
    
    # Pour utiliser un Dockerfile (Docker fera un Docker Build)
    build:
      context: ./ # Le nom du répertoire dans lequel se trouve le fichier Dockerfile
    image: angular
    
    container_name: projet-jardin-angular
    ports:
      - 81:80
    networks:
      - projet-jardin


networks:
  projet-jardin:
   driver: bridge
